# PW2-Data preparation :
#### A basic Machine Learning algorithms to Read/write files, deal with Missing, cleaning, and Impute data

In order to sucessfully run this notebook, you need to have the following files in the same folder as this notebook: "melb_data.csv", "olympic.csv", "olympic.csv"

## Part I: Data management with Pandas

### Exercise 1: Pandas Series data structure

In [2]:
import pandas as pd
sports = ['Football','HandBall', 'SnowSport']
pd.Series(sports)

0     Football
1     HandBall
2    SnowSport
dtype: object

In [ ]:
type(sports)

list

In [ ]:
numeric = [1,2,3]
pd.Series(numeric)

0    1
1    2
2    3
dtype: int64

In [ ]:
numeric=[None, 15,100]
# cast list as a Series
pd.Series(numeric)

0      NaN
1     15.0
2    100.0
dtype: float64

In [ ]:
# create list of sports
sports = ['BasketBall', 'HandBall', None]
# cast list as a Series
pd.Series(sports)

0    BasketBall
1      HandBall
2          None
dtype: object

In [10]:
#6. We shall correct the incomplete value None of sports by changing the None by NaN (Numpy.nan)
import numpy as np
np.isnan(np.nan)
sports = ["BasketBall", "HandBall", np.nan]
pd.Series(sports)

0    BasketBall
1      HandBall
2           NaN
dtype: object

In [ ]:
#7.Let construct our variable sports from a dictionary as follows: {’BasketBall’, ’HandBall’, ’Snowsport’,’baseBall’, ’Swimming’}. Cast the variable to a serie and store it a new variable sIndex. Display sIndex and call the function index on it. What did you remark
sindex = pd.Series({'bask': 'BasketBall', 'hand': 'HandBall', 'snow': 'Snowsport','base': 'baseBall','swim': 'Swimming'})
sindex.index

Index(['bask', 'hand', 'snow', 'base', 'swim'], dtype='object')

### Exercise 2: Series Querying
Let we consider the variable sports from a dictionary.

In [ ]:
np.isnan(np.nan)
sports = {'bask': 'BasketBall', 'hand': 'HandBall', 'snow': 'Snowsport','base': 'baseBall','swim': 'Swimming'}
#cast the list on a serie
sIndex=pd.Series(sports)
#display the serie
display(sIndex)
sIndex.index

bask    BasketBall
hand      HandBall
snow     Snowsport
base      baseBall
swim      Swimming
dtype: object

Index(['bask', 'hand', 'snow', 'base', 'swim'], dtype='object')

In [ ]:
# 1. Display the second element of the variable sports and find the element who has ’swim’. (use iloc[] to index location and loc[] to label location).
sindex.loc['swim']

'Swimming'

In [ ]:
# 2. Transform all items of your list sports in an uppercase characters (see Series.str.upper())
sindex.str.upper()

bask    BASKETBALL
hand      HANDBALL
snow     SNOWSPORT
base      BASEBALL
swim      SWIMMING
dtype: object

In [ ]:
# 3. write a simple loop to transform sports in an uppercase Characters

#The function don't really change the value of the list but do the same operations
for i in sindex :
    i.upper()

In [ ]:
# 4. compare the runtime between both solutions and explain the runtime gap (see %timeit which is an IPython magic function, which can be used to time a particular piece of code.)

%timeit sindex.str.upper()
%timeit for i in sindex : i.upper()

53.7 µs ± 2.64 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
1.75 µs ± 239 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [ ]:
# 5. compare the runtime between the function np.mean() and a loop to calculate the mean value of your numeric variable

#Solution 1 with vectorisation using np.mean()
numeric=[None, 15,100]
# cast list as a Series
num=pd.Series(numeric)
meanValue=np.mean(num)
print(meanValue)

#Solution 2 using a loop

def my_mean():
    meanValue = 0
    sum=0
    for item in num:
        if (item != None) : sum += item
    meanValue=sum/len(num)
    return meanValue

%timeit my_mean()
%timeit np.mean(num)

#Numpy is more faster even if we could espect this more complete function to verify more condition
#If I remember it is because use more closer to C array

57.5
4.23 µs ± 737 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
32.8 µs ± 5.21 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

## Part II: data checking

### Exercise 3: From CSV to DataFrame data structure

In [4]:
# 1. Load the file Pearson.csv and store its content into a dataframe variable pearson Data
#be carefull: you need the relative path to your file folder
pearson_Data =pd.read_csv("sample_data/custelers.csv", delimiter= ',')

In [5]:
# 2. Display the shape of your dataframe and display the header to understand the meaning of each column.
print(pearson_Data.shape)
custemers_Data.head(1)

(10000, 15)

,name,address,city,state,zip,phone,email,work,work address,work city,work state,work zipcode,work phone,work email,account created on
0,Deonte Stark,278 Mueller Plains,North Euna,Alabama,03404-4384,(180)940-9676x4495,shanna73@hotmail.com,Hahn-Mayer,8177 Weber Throughway Apt. 341,Jaronton,Maine,51589-1424,01240240340,heller.kirstin@glover.com,2001-09-06 06:15:24

In [6]:
# 3. Use the dataframe.columns to display the dictionary indexing your dat
custemers_Data.columns

Index(['name', 'address', 'city', 'state', 'zip', 'phone', 'email', 'work',
       'work address', 'work city', 'work state', 'work zipcode', 'work phone',
       'work email', 'account created on'],
      dtype='object')

### Exercise 4: Check missing values
Now we want to evaluate the number of missing data in the hole data. Display the total of missing values in each
column of pearson Data

In [7]:
# 1. You can use dataframe.isnull() and verctorization to sum missing values by each column
custemers_Data.isnull().sum()

name                    81
address               3365
city                  3374
state                 3365
zip                   3362
phone                 3366
email                 3363
work                  3390
work address          3383
work city             3378
work state            3390
work zipcode          3378
work phone            3377
work email            3359
account created on    3368
dtype: int64

In [8]:
# 2. Display the rows with missing values in the ’name’ column, you should have 81 rows
custemers_Data.loc[pearson_Data['name'].isnull()]

,name,address,city,state,zip,phone,email,work,work address,work city,work state,work zipcode,work phone,work email,account created on
148,NaN,558 Brycen Mission Suite 152,Cristmouth,Arkansas,52585-7480,+03(6)2449148729,corene08@gmail.com,Braun PLC,8795 Carissa Land Apt. 884,South Arachester,New Mexico,68070-4086,09359769734,hezzie.hettinger@mcglynnlarson.com,1999-12-12
273,NaN,0481 Sanford Lake Apt. 439,Bashirianberg,North Carolina,61948-9865,(967)713-7747x7329,hermiston.jenniffer@hotmail.com,Grant LLC,7375 Lynn Fork,Wuckerthaven,Ohio,89342-4989,419-132-5389,colin.walsh@hane.com,1995-08-07 19:52:30
300,NaN,38689 Kimora Groves Suite 807,New Nadiahaven,Vermont,99133-2546,595.341.7775x50639,sfritsch@yahoo.com,Purdy-Farrell,29365 Nyah Flats,West Isabella,Florida,06342,+66(4)7117753075,ocrooks@mohr.net,1975-04-07
330,NaN,077 Walsh Summit Suite 123,Rogahnfurt,Indiana,81369,+38(1)3931574807,tdenesik@hotmail.com,Corwin-Fahey,717 Karol Stravenue Apt. 964,Trantowhaven,Utah,49873-6641,882.577.0021x2495,mschaden@gerholdschultz.net,03/10/2010
467,NaN,87140 Loma Crescent,North Dixieport,Michigan,32196-8397,+65(0)2946604451,lucille69@gmail.com,Monahan Ltd,99220 Murphy Motorway,East Reyhaven,Rhode Island,50641,773.245.8906,parisian.willard@feil.org,04/29/1986
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9316,NaN,054 Aubrie Corners,East Genevieve,New Hampshire,92371,296-242-9406x586,enrico.kuvalis@yahoo.com,Schneider LLC,53056 Gaige Motorway,North Audriana,Arkansas,73816,605.101.0879,cephus.conroy@schroeder.com,01/21/2000
9487,NaN,9957 Rempel Wells Apt. 081,New Micky,Alabama,24013,522-665-0735,rylan47@hotmail.com,Bergnaum and Sons,60120 Klocko Alley Apt. 615,Adalineport,Maryland,37182-8209,289.393.5802x9949,mwolf@corwin.net,2000-09-07
9745,NaN,6277 Schneider Common Suite 939,Port Aura,North Dakota,10127,127.858.7550,kacy29@gmail.com,Becker PLC,186 Armstrong Lakes,East Rosalyn,Ohio,07576,1-924-436-1559x850,kunde.carry@auerweimann.org,1995-08-13 11:03:45
9816,NaN,986 Brianne Shoals,Port Wilbertstad,Mississippi,99396,953.475.7297x373,ritchie.hadley@yahoo.com,Kautzer-Batz,22243 Feil Terrace Suite 469,New Catofurt,Wisconsin,62178,09723145605,thompson.eulalie@mann.com,1970-01-27 16:26:56
9834,NaN,19233 Kreiger Meadow,Kleinville,Michigan,42537-0382,(894)710-7706x071,hjalmer14@hotmail.com,Beer-Ledner,48801 Bobbye Roads,West Tylor,Arkansas,60338,849.567.9201x682,hsatterfield@bradtke.com,2015-10-13 23:24:40

In [13]:
# 3. Try removing rows with missing names. We call dropna() function which has many arguments to scale the level of a filtered data:
#self_filtered_data = pearson_Data[(pearson_Data.isnull()== False)@np.ones(15, dtype= bool)]
self_filtered_data = custemers_Data[(custemers_Data.isnull()== False)]
self_filtered_data

,name,address,city,state,zip,phone,email,work,work address,work city,work state,work zipcode,work phone,work email,account created on
0,Deonte Stark,278 Mueller Plains,North Euna,Alabama,03404-4384,(180)940-9676x4495,shanna73@hotmail.com,Hahn-Mayer,8177 Weber Throughway Apt. 341,Jaronton,Maine,51589-1424,01240240340,heller.kirstin@glover.com,2001-09-06 06:15:24
1,Faustino Boyer,70244 Skiles Falls Suite 030,North Altohaven,California,01522-1310,(308)699-6239x81011,ferrell81@gmail.com,Buckridge Inc,236 Kessler Center,New Gavynshire,Missouri,52234-6972,(486)896-6855x446,esta.dicki@bechtelar.com,1983-04-25
2,"Eddy Bogisich,33431 Dollie Squares Apt. 654,Po...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mervyn Kreiger,376 Dorinda Stream,Shaniquafort,South Carolina,39347-4438,869-985-6299,emmerich.griselda@hotmail.com,Witting PLC,521 Kemmer Manors,Nerytown,Kentucky,68774,(212)169-8190,greyson39@purdy.com,1971-04-27 14:05:06
4,"Katlyn Doyle,4650 Beer Crossing Suite 848,Nort...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Ciera Wunsch,25198 Fernando Isle Suite 175,South Pricillashire,Colorado,53222-8926,005-769-2290x3662,shannon.beatty@gmail.com,Metz-Kub,28254 Nikolaus Plains,West Emmitthaven,Minnesota,34939-5981,(154)316-2907x520,clemente.dach@leannon.com,1986-11-14
9996,Beula Bauch,800 Keebler Stream,East Denise,Maine,33693,933.047.0305,steuber.zakary@hotmail.com,Barrows Inc,35083 Champlin Keys Suite 030,Port Yulisa,Rhode Island,35745,(148)771-5153x521,windler.trudi@shanahanhagenes.org,2013-11-02 20:50:10
9997,Garvin Runolfsson,4844 Dietrich Islands Suite 457,Auerport,Michigan,34497,312.046.9856,nwehner@hotmail.com,Braun Inc,7514 Samiyah Brooks,West Ham,Texas,90804,388-879-8433x7099,stamm.erlene@stoltenberg.org,2008-04-13
9998,Hildegarde Gleichner,96841 Predovic Locks,New Knute,Rhode Island,88719-7033,269-922-1275,ksatterfield@yahoo.com,Turcotte LLC,NaN,Medhurstside,Oregon,20523-8984,863.095.3340x2593,coby06@kulasbogan.com,1990-02-20
9999,"Rhett Spinka,87035 Solon Prairie,Zelmahaven,Ha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
custemers_Data.dropna(how="all", inplace=True)
custemers_Data

,name,address,city,state,zip,phone,email,work,work address,work city,work state,work zipcode,work phone,work email,account created on
0,Deonte Stark,278 Mueller Plains,North Euna,Alabama,03404-4384,(180)940-9676x4495,shanna73@hotmail.com,Hahn-Mayer,8177 Weber Throughway Apt. 341,Jaronton,Maine,51589-1424,01240240340,heller.kirstin@glover.com,2001-09-06 06:15:24
1,Faustino Boyer,70244 Skiles Falls Suite 030,North Altohaven,California,01522-1310,(308)699-6239x81011,ferrell81@gmail.com,Buckridge Inc,236 Kessler Center,New Gavynshire,Missouri,52234-6972,(486)896-6855x446,esta.dicki@bechtelar.com,1983-04-25
2,"Eddy Bogisich,33431 Dollie Squares Apt. 654,Po...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mervyn Kreiger,376 Dorinda Stream,Shaniquafort,South Carolina,39347-4438,869-985-6299,emmerich.griselda@hotmail.com,Witting PLC,521 Kemmer Manors,Nerytown,Kentucky,68774,(212)169-8190,greyson39@purdy.com,1971-04-27 14:05:06
4,"Katlyn Doyle,4650 Beer Crossing Suite 848,Nort...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Ciera Wunsch,25198 Fernando Isle Suite 175,South Pricillashire,Colorado,53222-8926,005-769-2290x3662,shannon.beatty@gmail.com,Metz-Kub,28254 Nikolaus Plains,West Emmitthaven,Minnesota,34939-5981,(154)316-2907x520,clemente.dach@leannon.com,1986-11-14
9996,Beula Bauch,800 Keebler Stream,East Denise,Maine,33693,933.047.0305,steuber.zakary@hotmail.com,Barrows Inc,35083 Champlin Keys Suite 030,Port Yulisa,Rhode Island,35745,(148)771-5153x521,windler.trudi@shanahanhagenes.org,2013-11-02 20:50:10
9997,Garvin Runolfsson,4844 Dietrich Islands Suite 457,Auerport,Michigan,34497,312.046.9856,nwehner@hotmail.com,Braun Inc,7514 Samiyah Brooks,West Ham,Texas,90804,388-879-8433x7099,stamm.erlene@stoltenberg.org,2008-04-13
9998,Hildegarde Gleichner,96841 Predovic Locks,New Knute,Rhode Island,88719-7033,269-922-1275,ksatterfield@yahoo.com,Turcotte LLC,NaN,Medhurstside,Oregon,20523-8984,863.095.3340x2593,coby06@kulasbogan.com,1990-02-20
9999,"Rhett Spinka,87035 Solon Prairie,Zelmahaven,Ha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
custemers_Data.dropna(inplace=True, axis=0)
custemers_Data

,name,address,city,state,zip,phone,email,work,work address,work city,work state,work zipcode,work phone,work email,account created on
0,Deonte Stark,278 Mueller Plains,North Euna,Alabama,03404-4384,(180)940-9676x4495,shanna73@hotmail.com,Hahn-Mayer,8177 Weber Throughway Apt. 341,Jaronton,Maine,51589-1424,01240240340,heller.kirstin@glover.com,2001-09-06 06:15:24
1,Faustino Boyer,70244 Skiles Falls Suite 030,North Altohaven,California,01522-1310,(308)699-6239x81011,ferrell81@gmail.com,Buckridge Inc,236 Kessler Center,New Gavynshire,Missouri,52234-6972,(486)896-6855x446,esta.dicki@bechtelar.com,1983-04-25
3,Mervyn Kreiger,376 Dorinda Stream,Shaniquafort,South Carolina,39347-4438,869-985-6299,emmerich.griselda@hotmail.com,Witting PLC,521 Kemmer Manors,Nerytown,Kentucky,68774,(212)169-8190,greyson39@purdy.com,1971-04-27 14:05:06
5,Daquan Leffler,43142 Howell Ports Apt. 953,West Emory,Connecticut,08086-5571,874-576-0739,natosha.kutch@yahoo.com,Christiansen Ltd,3136 Jered Junction Suite 993,West Mallie,New Hampshire,40778-7891,215.605.7824x844,anderson.gifford@nader.com,2014-01-15 23:15:43
6,Jace Konopelski,963 Senger Points Apt. 992,Lake Fonda,North Dakota,15581,(083)182-4626x8012,langosh.mathilde@hotmail.com,Glover-Howe,87986 Harvey Islands,South Zackary,Kentucky,75232-9391,(270)125-2639,kassulke.fate@hills.com,05/20/2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,Tawnya Williamson,4160 Welch Roads,Amasahaven,Maine,76161,1-468-320-0246x8915,doreilly@yahoo.com,Schuster-Lemke,82853 Watsica View,South Jaydan,Georgia,54467-3704,264-477-5271,donell95@wilderman.com,1974-07-22
9993,Cayla Gleason,505 Rogahn Trafficway,New Sabastian,Tennessee,56989-4233,(578)118-9244x85865,mtorp@gmail.com,Morissette Group,484 Lubowitz Inlet Suite 138,East Sannieland,North Carolina,66018,892-930-2586x31401,bina.pagac@johns.com,1996-04-08
9995,Ciera Wunsch,25198 Fernando Isle Suite 175,South Pricillashire,Colorado,53222-8926,005-769-2290x3662,shannon.beatty@gmail.com,Metz-Kub,28254 Nikolaus Plains,West Emmitthaven,Minnesota,34939-5981,(154)316-2907x520,clemente.dach@leannon.com,1986-11-14
9996,Beula Bauch,800 Keebler Stream,East Denise,Maine,33693,933.047.0305,steuber.zakary@hotmail.com,Barrows Inc,35083 Champlin Keys Suite 030,Port Yulisa,Rhode Island,35745,(148)771-5153x521,windler.trudi@shanahanhagenes.org,2013-11-02 20:50:10
9997,Garvin Runolfsson,4844 Dietrich Islands Suite 457,Auerport,Michigan,34497,312.046.9856,nwehner@hotmail.com,Braun Inc,7514 Samiyah Brooks,West Ham,Texas,90804,388-879-8433x7099,stamm.erlene@stoltenberg.org,2008-04-13

The dropna show the same result that the intuitive moove to remove all the rows with a null value.
Also we figured out that dropna with how = "all" showed no change wich mean there are not null rows on our dataframe.

### Exercise 5: Ensure that values have the right format/type
If we take the ”name” column, we find the first name and the last name separated with a blank character

In [ ]:
# 1. check the type of each column using the function astype()
custemers_Data.astype(dtype = 'string')

,name,address,city,state,zip,phone,email,work,work address,work city,work state,work zipcode,work phone,work email,account created on
0,Deonte Stark,278 Mueller Plains,North Euna,Alabama,03404-4384,(180)940-9676x4495,shanna73@hotmail.com,Hahn-Mayer,8177 Weber Throughway Apt. 341,Jaronton,Maine,51589-1424,01240240340,heller.kirstin@glover.com,2001-09-06 06:15:24
1,Faustino Boyer,70244 Skiles Falls Suite 030,North Altohaven,California,01522-1310,(308)699-6239x81011,ferrell81@gmail.com,Buckridge Inc,236 Kessler Center,New Gavynshire,Missouri,52234-6972,(486)896-6855x446,esta.dicki@bechtelar.com,1983-04-25
3,Mervyn Kreiger,376 Dorinda Stream,Shaniquafort,South Carolina,39347-4438,869-985-6299,emmerich.griselda@hotmail.com,Witting PLC,521 Kemmer Manors,Nerytown,Kentucky,68774,(212)169-8190,greyson39@purdy.com,1971-04-27 14:05:06
5,Daquan Leffler,43142 Howell Ports Apt. 953,West Emory,Connecticut,08086-5571,874-576-0739,natosha.kutch@yahoo.com,Christiansen Ltd,3136 Jered Junction Suite 993,West Mallie,New Hampshire,40778-7891,215.605.7824x844,anderson.gifford@nader.com,2014-01-15 23:15:43
6,Jace Konopelski,963 Senger Points Apt. 992,Lake Fonda,North Dakota,15581,(083)182-4626x8012,langosh.mathilde@hotmail.com,Glover-Howe,87986 Harvey Islands,South Zackary,Kentucky,75232-9391,(270)125-2639,kassulke.fate@hills.com,05/20/2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,Tawnya Williamson,4160 Welch Roads,Amasahaven,Maine,76161,1-468-320-0246x8915,doreilly@yahoo.com,Schuster-Lemke,82853 Watsica View,South Jaydan,Georgia,54467-3704,264-477-5271,donell95@wilderman.com,1974-07-22
9993,Cayla Gleason,505 Rogahn Trafficway,New Sabastian,Tennessee,56989-4233,(578)118-9244x85865,mtorp@gmail.com,Morissette Group,484 Lubowitz Inlet Suite 138,East Sannieland,North Carolina,66018,892-930-2586x31401,bina.pagac@johns.com,1996-04-08
9995,Ciera Wunsch,25198 Fernando Isle Suite 175,South Pricillashire,Colorado,53222-8926,005-769-2290x3662,shannon.beatty@gmail.com,Metz-Kub,28254 Nikolaus Plains,West Emmitthaven,Minnesota,34939-5981,(154)316-2907x520,clemente.dach@leannon.com,1986-11-14
9996,Beula Bauch,800 Keebler Stream,East Denise,Maine,33693,933.047.0305,steuber.zakary@hotmail.com,Barrows Inc,35083 Champlin Keys Suite 030,Port Yulisa,Rhode Island,35745,(148)771-5153x521,windler.trudi@shanahanhagenes.org,2013-11-02 20:50:10
9997,Garvin Runolfsson,4844 Dietrich Islands Suite 457,Auerport,Michigan,34497,312.046.9856,nwehner@hotmail.com,Braun Inc,7514 Samiyah Brooks,West Ham,Texas,90804,388-879-8433x7099,stamm.erlene@stoltenberg.org,2008-04-13

In [ ]:
# 2. Let we split the column ’name’ into two columns where the first string is the first name and the second string is the last name. (see str.split()).
custemers_Data['name'].str.split(" ")

0              [Deonte, Stark]
1            [Faustino, Boyer]
3            [Mervyn, Kreiger]
5            [Daquan, Leffler]
6         [, Jace, Konopelski]
                 ...
9991      [Tawnya, Williamson]
9993        [, Cayla, Gleason]
9995           [Ciera, Wunsch]
9996          [, Beula, Bauch]
9997    [, Garvin, Runolfsson]
Name: name, Length: 5657, dtype: object

In [ ]:
# 3. You can remark incorrect lastname values. Remove rows having lastname length up to 16 characters. Take 5 mn to outline the main ideas you’ve retained from these exercises (Part I and
custemers_Data = custemers_Data[[len(x) == 2 for x in custemers_Data['name'].str.split(" ") ]]
custemers_Data['name'].str.split(" ")

0             [Deonte, Stark]
1           [Faustino, Boyer]
3           [Mervyn, Kreiger]
5           [Daquan, Leffler]
8             [Katlin, Robel]
                ...
9986    [Mechelle, Schneider]
9988          [Dorthy, Price]
9989          [Emmet, Renner]
9991     [Tawnya, Williamson]
9995          [Ciera, Wunsch]
Name: name, Length: 2794, dtype: object

## Part III: Data repairing with imputation

### Exercise 6 Version FLICKR: Do it from scratch at home and upload it on Moodle

Import the dataset

In [ ]:
df = pd.read_csv("BL-Flickr-Images-Book-subset.csv")

What is the shape of our dataframe ?

In [ ]:
df.shape

(8286, 14)

What are the columns of our dataframe ?

In [ ]:

df.columns

Index(['Identifier', 'Edition Statement', 'Place of Publication',
       'Date of Publication', 'Publisher', 'Title', 'Author', 'Contributors',
       'Corporate Author', 'Corporate Contributors', 'Former owner',
       'Engraver', 'Issuance type', 'Flickr URL', 'Shelfmarks'],
      dtype='object')

Let's display a couple of values

In [ ]:
df.head(5)

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

What is the type and if there is missing values ?

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8287 entries, 0 to 8286
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Identifier              8287 non-null   int64
 1   Edition Statement       773 non-null    object
 2   Place of Publication    8287 non-null   object
 3   Date of Publication     8106 non-null   object
 4   Publisher               4092 non-null   object
 5   Title                   8287 non-null   object
 6   Author                  6509 non-null   object
 7   Contributors            8287 non-null   object
 8   Corporate Author        0 non-null      float64
 9   Corporate Contributors  0 non-null      float64
 10  Former owner            1 non-null      object
 11  Engraver                0 non-null      float64
 12  Issuance type           8287 non-null   object
 13  Flickr URL              8287 non-null   object
 14  Shelfmarks              8287 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 971.3+ KB

We identify that the 1 and 7 to 10 are almost missing values, let's drop them. Let's also drop the publisher wich is null for the half of the values.

In [ ]:
df.drop(['Edition Statement', 'Corporate Author', 'Corporate Contributors', 'Former owner', 'Publisher' ,'Engraver'], inplace=True, axis=1)

The we can just drop the few lines of the dataframe with missing values

In [ ]:
df.dropna( inplace=True, axis=0)

Now we want to clean the date of publication column

In [ ]:
#Clean the date of publication
extr = df['Date of Publication'].astype(str).str.extract(r'^(\d{4})', expand=False)
df['Date of Publication'] = pd.to_numeric(extr)

In [ ]:
df['Date of Publication']

0       1879
1       1868
2       1869
3       1851
4       1857
        ...
8280    1811
8281    1867
8282    1838
8283    1831
8285    1834
Name: Date of Publication, Length: 5782, dtype: int64

Finally we have a clean dataset

In [ ]:
df.head(5)

,Identifier,Place of Publication,Date of Publication,Title,Author,Contributors,Issuance type,Flickr URL,Shelfmarks
0,206,London,1879,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,London; Virtue & Yorston,1868,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,London,1869,Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,London,1851,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,London,1857,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

### Exercise 6 Version OLYMPIC: Do it from scratch at home and upload it on Moodle

In [ ]:
df = pd.read_csv("olympic.csv", index_col=0, skiprows=1)
#Fist lets display a couple of values
df.head()

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [ ]:
#What is the shape of our dataframe
df.shape

(147, 15)

In [ ]:
#What is the type and the names of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 147 entries, Afghanistan (AFG) to Totals
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   № Summer        147 non-null    int64
 1   01 !            147 non-null    int64
 2   02 !            147 non-null    int64
 3   03 !            147 non-null    int64
 4   Total           147 non-null    int64
 5   № Winter        147 non-null    int64
 6   01 !.1          147 non-null    int64
 7   02 !.1          147 non-null    int64
 8   03 !.1          147 non-null    int64
 9   Total.1         147 non-null    int64
 10  № Games         147 non-null    int64
 11  01 !.2          147 non-null    int64
 12  02 !.2          147 non-null    int64
 13  03 !.2          147 non-null    int64
 14  Combined total  147 non-null    int64
dtypes: int64(15)
memory usage: 18.4+ KB

In [ ]:
# Do we need to clean our data ?
df.isnull().sum()

№ Summer          0
01 !              0
02 !              0
03 !              0
Total             0
№ Winter          0
01 !.1            0
02 !.1            0
03 !.1            0
Total.1           0
№ Games           0
01 !.2            0
02 !.2            0
03 !.2            0
Combined total    0
dtype: int64

In [ ]:
#There are no missing values in our dataset but if the number of games is equal to zero we can remove the row
(df['№ Games'] == 0).sum()

0

Our data seems clean so we can start to analyse it

In [ ]:
df.describe()

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
count,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000
mean,13.476190,65.428571,64.965986,69.795918,200.190476,6.700680,13.047619,13.034014,12.897959,38.979592,20.176871,78.476190,78.000000,82.693878,239.170068
std,7.072359,405.549990,399.309960,427.187344,1231.306297,7.433186,80.799204,80.634421,79.588388,240.917324,13.257048,485.013378,478.860334,505.855110,1469.067883
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.000000,0.000000,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.000000,0.000000,1.000000,1.000000,2.500000
50%,13.000000,3.000000,4.000000,6.000000,12.000000,5.000000,0.000000,0.000000,0.000000,0.000000,15.000000,3.000000,4.000000,7.000000,12.000000
75%,18.500000,24.000000,28.000000,29.000000,86.000000,10.000000,1.000000,2.000000,1.000000,5.000000,27.000000,25.500000,29.000000,32.500000,89.000000
max,27.000000,4809.000000,4775.000000,5130.000000,14714.000000,22.000000,959.000000,958.000000,948.000000,2865.000000,49.000000,5768.000000,5733.000000,6078.000000,17579.000000

In [ ]:
#Let's short the dataset by the number of combined medals
df.sort_values(by='Combined total', ascending=False).head(10)

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579
United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
Soviet Union (URS) [URS],9,395,319,296,1010,9,78,57,59,194,18,473,376,355,1204
Great Britain (GBR) [GBR] [Z],27,236,272,272,780,22,10,4,12,26,49,246,276,284,806
Germany (GER) [GER] [Z],15,174,182,217,573,11,78,78,53,209,26,252,260,270,782
France (FRA) [O] [P] [Z],27,202,223,246,671,22,31,31,47,109,49,233,254,293,780
Italy (ITA) [M] [S],26,198,166,185,549,22,37,34,43,114,48,235,200,228,663
Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
Russia (RUS) [RUS],5,132,121,142,395,6,49,40,35,124,11,181,161,177,519

### Exercise 7: Imputation to handle missing data
In this exercise we will compare two solutions of data cleaning. The first one consists to drop missing columns values while the second is to fill missing values with interesting ones. In your notebook, open the file melb data.csv.

In [ ]:
# 1. load your data as a dataframe and use a clear name as ”initialData”
initialData = pd.read_csv("melb_data.csv")

In [ ]:
# 2. observe first the quality of the data by using these functions: dataframe.columns, dataframe.info(), and dataframe.shape.
initialData.columns

Index(['Unnamed: 0', 'Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method',
       'SellerG', 'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom',
       'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea',
       'Lattitude', 'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [ ]:
initialData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18396 entries, 0 to 18395
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     18396 non-null  int64
 1   Suburb         18396 non-null  object
 2   Address        18396 non-null  object
 3   Rooms          18396 non-null  int64
 4   Type           18396 non-null  object
 5   Price          18396 non-null  float64
 6   Method         18396 non-null  object
 7   SellerG        18396 non-null  object
 8   Date           18396 non-null  object
 9   Distance       18395 non-null  float64
 10  Postcode       18395 non-null  float64
 11  Bedroom2       14927 non-null  float64
 12  Bathroom       14925 non-null  float64
 13  Car            14820 non-null  float64
 14  Landsize       13603 non-null  float64
 15  BuildingArea   7762 non-null   float64
 16  YearBuilt      8958 non-null   float64
 17  CouncilArea    12233 non-null  object
 18  Lattitude      15064 non-null  float64
 19  Longtitude     15064 non-null  float64
 20  Regionname     18395 non-null  object
 21  Propertycount  18395 non-null  float64
dtypes: float64(12), int64(2), object(8)
memory usage: 3.1+ MB

In [ ]:
initialData.shape

(18396, 22)

In [ ]:
# 3. display the total missing values by columns (axis=0)
initialData.isnull().sum( axis= 0)

Unnamed: 0           0
Suburb               0
Address              0
Rooms                0
Type                 0
Price                0
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          3469
Bathroom          3471
Car               3576
Landsize          4793
BuildingArea     10634
YearBuilt         9438
CouncilArea       6163
Lattitude         3332
Longtitude        3332
Regionname           1
Propertycount        1
dtype: int64

In [ ]:
# 4. display total missing Values by rows (axis=1)
initialData.isnull().sum(axis = 1)

0        2
1        0
2        0
3        2
4        0
        ..
18391    2
18392    1
18393    4
18394    1
18395    2
Length: 18396, dtype: int64

In [ ]:
# 5. list the columns with missing values and store them in a variable colsWithMissing. Use the function isnull() and try to write a simple function you can call it with other datasets with the following signature and core code as following:

'''
def missing_colums(originDB):
    colsWithMissing = originDB[originDB.isnull() @ np.ones(np.size(originDB, 1), dtype = bool)]
    reduced_original_data = originDB[(originDB.isnull() @ np.ones(np.size(originDB, 1), dtype = bool)) == False]
    return colsWithMissing, reduced_original_data
'''

def missing_colums(originDB):
    colsWithMissing = [col for col in originDB.columns if originDB[col].isnull().any()]
    reduced_original_data = originDB.drop(colsWithMissing, axis=1)
    return colsWithMissing, reduced_original_data

In [ ]:
#If those columns had relevant information your model loses access to it when the column is dropped. Another drawback to this solution is to miss to do the same droping on the test dataset where an error will occur.
# 6. display the rate of missing values by columns
initialData.isnull().mean( axis= 0)

Unnamed: 0       0.000000
Suburb           0.000000
Address          0.000000
Rooms            0.000000
Type             0.000000
Price            0.000000
Method           0.000000
SellerG          0.000000
Date             0.000000
Distance         0.000054
Postcode         0.000054
Bedroom2         0.188574
Bathroom         0.188682
Car              0.194390
Landsize         0.260546
BuildingArea     0.578060
YearBuilt        0.513046
CouncilArea      0.335018
Lattitude        0.181126
Longtitude       0.181126
Regionname       0.000054
Propertycount    0.000054
dtype: float64

In [ ]:
# 7. do the same on the rows
initialData.isnull().mean( axis= 1)

0        0.090909
1        0.000000
2        0.000000
3        0.090909
4        0.000000
           ...
18391    0.090909
18392    0.045455
18393    0.181818
18394    0.045455
18395    0.090909
Length: 18396, dtype: float64

In [ ]:
initialData

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18391,23540,Williamstown,8/2 Thompson St,2,t,622500.0,SP,Greg,26/08/2017,6.8,...,2.0,1.0,NaN,89.0,2010.0,NaN,-37.86393,144.90484,Western Metropolitan,6380.0
18392,23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
18393,23544,Yallambie,17 Amaroo Wy,4,h,1100000.0,S,Buckingham,26/08/2017,12.7,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
18394,23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
18395,23546,Yarraville,33 Freeman St,4,h,1050000.0,VB,Village,26/08/2017,6.3,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

In [ ]:
# 8. remove rows whom the rate of missing values are > 5% from the origin data and store the result on a new dataframe variable named new Data.
new_data = initialData.drop(initialData.index[initialData.isnull().mean( axis= 1) > 0.05], axis = 0)
new_data

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
1,2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
4,6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
6,11,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,...,2.0,0.0,245.0,210.0,1910.0,Yarra,-37.80240,144.99930,Northern Metropolitan,4019.0
7,14,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,8/10/2016,2.5,...,1.0,2.0,256.0,107.0,1890.0,Yarra,-37.80600,144.99540,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18382,23527,Watsonia,76 Kenmare St,2,h,650000.0,PI,Morrison,26/08/2017,14.5,...,1.0,1.0,210.0,79.0,2006.0,NaN,-37.70657,145.07878,Northern Metropolitan,2329.0
18384,23532,Werribee,5 Nuragi Ct,4,h,635000.0,S,hockingstuart,26/08/2017,14.7,...,2.0,1.0,662.0,172.0,1980.0,NaN,-37.89327,144.64789,Western Metropolitan,16166.0
18389,23538,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
18392,23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
18394,23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [ ]:
# 9. call your function missing colums(originDB) on both original data and on new data obtained after removal rows. How do you explain the columns difference?
colsWithMissing, reduced_original_data = missing_colums(initialData)
reduced_original_data

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date
0,1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016
1,2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016
2,4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017
3,5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017
4,6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016
...,...,...,...,...,...,...,...,...,...
18391,23540,Williamstown,8/2 Thompson St,2,t,622500.0,SP,Greg,26/08/2017
18392,23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017
18393,23544,Yallambie,17 Amaroo Wy,4,h,1100000.0,S,Buckingham,26/08/2017
18394,23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017
18395,23546,Yarraville,33 Freeman St,4,h,1050000.0,VB,Village,26/08/2017

In [ ]:
new_colsWithMissing, reduced_new_data = missing_colums(new_data)
reduced_new_data

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,Lattitude,Longtitude,Regionname,Propertycount
1,2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,-37.80790,144.99340,Northern Metropolitan,4019.0
2,4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,-37.80930,144.99440,Northern Metropolitan,4019.0
4,6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,3.0,1.0,2.0,120.0,-37.80720,144.99410,Northern Metropolitan,4019.0
6,11,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,4.0,2.0,0.0,245.0,-37.80240,144.99930,Northern Metropolitan,4019.0
7,14,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,8/10/2016,2.5,3067.0,2.0,1.0,2.0,256.0,-37.80600,144.99540,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18382,23527,Watsonia,76 Kenmare St,2,h,650000.0,PI,Morrison,26/08/2017,14.5,3087.0,2.0,1.0,1.0,210.0,-37.70657,145.07878,Northern Metropolitan,2329.0
18384,23532,Werribee,5 Nuragi Ct,4,h,635000.0,S,hockingstuart,26/08/2017,14.7,3030.0,4.0,2.0,1.0,662.0,-37.89327,144.64789,Western Metropolitan,16166.0
18389,23538,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,3.0,2.0,2.0,333.0,-37.85927,144.87904,Western Metropolitan,6380.0
18392,23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,4.0,1.0,5.0,866.0,-37.85908,144.89299,Western Metropolitan,6380.0
18394,23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,4.0,1.0,1.0,362.0,-37.81188,144.88449,Western Metropolitan,6543.0

The difference could be explained by remooving error rows with a lot of missing value making mean of multiple columns increasing without meaning that a coloms is particularly problematic.

In [ ]:
# 10. fill the missing values with the mean price, so you have to: 1) Display the statistical description of the column Price using the function describe(), 2) then to calculate the mean value and 3) to fill the missing value with the mean:
#myself :
initialData.describe()
mean_price = initialData['Price'].mean()
filled_Data = initialData.copy()
filled_Data[filled_Data.isnull()] = mean_price

#course
new_data.loc[:,"Price"].describe()
new_data["Price"].mean()
new_data.loc[:,"Price"].fillna(new_data["Price"].mean(),inplace=True)

### Exercise 8: Transformer and Pipeline with scikitlearn for Imputation processing
In the previous exercise, we have decided to estimate the missing values using the mean estimator and fill missing
values with the same value. However the imputation is an estimation of the data with a defined strategy as
the median, the mean, variance, etc. Scikitlearn API provides an simple class to take care of missing values:

In [ ]:
# SimpleImputer. To use this class, we have to create a SimpleImputer instance by specifying the strategy
from sklearn.impute import SimpleImputer
my_imputer = SimpleImputer(strategy="mean")

In [ ]:
# since the mean could be calculated only on numerical attributes, you need to create a copy of the data without the text attributes. You call this copy as a origin Data Num
# Then you have to fit the mean on your origin Data Num
Origin_Data_num= initialData.drop(columns= initialData.select_dtypes(include=["object"]).columns).copy()
my_imputer.fit(Origin_Data_num)

SimpleImputer()

In [ ]:
#the fit() function stores the result into its statistic instance variable. At any moment you can reuse this variable to repair new missing values. You can display this variable: imputer.statistics
my_imputer.statistics_

array([ 1.18267871e+04,  2.93504023e+00,  1.05669746e+06,  1.03899864e+01,
        3.10714015e+03,  2.91304348e+00,  1.53849246e+00,  1.61551957e+00,
        5.58116371e+02,  1.51220219e+02,  1.96588000e+03, -3.78098491e+01,
        1.44996338e+02,  7.51797527e+03])

In [ ]:
# finaly You use the imputer to transform the numerical data:
Transform_Data_num = my_imputer.transform(Origin_Data_num)

In [ ]:
df_Transform_Data_num=pd.DataFrame(Transform_Data_num, columns= Origin_Data_num.columns , index = Origin_Data_num.index )

In [ ]:
df_Transform_Data_num

,Unnamed: 0,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
0,1.0,2.0,1480000.0,2.5,3067.0,2.0,1.0,1.0,202.000000,151.220219,1965.879996,-37.79960,144.99840,4019.0
1,2.0,2.0,1035000.0,2.5,3067.0,2.0,1.0,0.0,156.000000,79.000000,1900.000000,-37.80790,144.99340,4019.0
2,4.0,3.0,1465000.0,2.5,3067.0,3.0,2.0,0.0,134.000000,150.000000,1900.000000,-37.80930,144.99440,4019.0
3,5.0,3.0,850000.0,2.5,3067.0,3.0,2.0,1.0,94.000000,151.220219,1965.879996,-37.79690,144.99690,4019.0
4,6.0,4.0,1600000.0,2.5,3067.0,3.0,1.0,2.0,120.000000,142.000000,2014.000000,-37.80720,144.99410,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18391,23540.0,2.0,622500.0,6.8,3016.0,2.0,2.0,1.0,558.116371,89.000000,2010.000000,-37.86393,144.90484,6380.0
18392,23541.0,4.0,2500000.0,6.8,3016.0,4.0,1.0,5.0,866.000000,157.000000,1920.000000,-37.85908,144.89299,6380.0
18393,23544.0,4.0,1100000.0,12.7,3085.0,4.0,3.0,2.0,558.116371,151.220219,1965.879996,-37.72006,145.10547,1369.0
18394,23545.0,4.0,1285000.0,6.3,3013.0,4.0,1.0,1.0,362.000000,112.000000,1920.000000,-37.81188,144.88449,6543.0
18395,23546.0,4.0,1050000.0,6.3,3013.0,4.0,2.0,2.0,558.116371,139.000000,1950.000000,-37.81829,144.87404,6543.0

### Exercise 9: to learn more
You can create a pipeline to automate the cleaning process using the pipe and imputer. Reshape your code to 1) create a pipeline to handle numerical data and an other pipeline to handle categorical data

In [ ]:
# SimpleImputer. To use this class, we have to create a SimpleImputer instance by specifying the strategy
from sklearn.impute import SimpleImputer
my_numerical_imputer = SimpleImputer(strategy="mean")
my_categorical_imputer = SimpleImputer(strategy="most_frequent")
Origin_Data_num= initialData.select_dtypes(include=["int64", "float64"]).copy()
Origin_Data_log= initialData.select_dtypes(include=["object"]).copy()
my_numerical_imputer.fit(Origin_Data_num)
my_categorical_imputer.fit(Origin_Data_log)
Transform_Data_num = my_numerical_imputer.transform(Origin_Data_num)
Transform_Data_log = my_categorical_imputer.transform(Origin_Data_log)
df_Transform_Data_num=pd.DataFrame(Transform_Data_num, columns= Origin_Data_num.columns , index = Origin_Data_num.index )
df_Transform_Data_log=pd.DataFrame(Transform_Data_log, columns= Origin_Data_log.columns , index = Origin_Data_log.index )
df_Transform_Data = pd.concat([df_Transform_Data_num, df_Transform_Data_log], axis=1)
df_Transform_Data

,Unnamed: 0,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,...,Longtitude,Propertycount,Suburb,Address,Type,Method,SellerG,Date,CouncilArea,Regionname
0,1.0,2.0,1480000.0,2.5,3067.0,2.0,1.0,1.0,202.000000,151.220219,...,144.99840,4019.0,Abbotsford,85 Turner St,h,S,Biggin,3/12/2016,Yarra,Northern Metropolitan
1,2.0,2.0,1035000.0,2.5,3067.0,2.0,1.0,0.0,156.000000,79.000000,...,144.99340,4019.0,Abbotsford,25 Bloomburg St,h,S,Biggin,4/02/2016,Yarra,Northern Metropolitan
2,4.0,3.0,1465000.0,2.5,3067.0,3.0,2.0,0.0,134.000000,150.000000,...,144.99440,4019.0,Abbotsford,5 Charles St,h,SP,Biggin,4/03/2017,Yarra,Northern Metropolitan
3,5.0,3.0,850000.0,2.5,3067.0,3.0,2.0,1.0,94.000000,151.220219,...,144.99690,4019.0,Abbotsford,40 Federation La,h,PI,Biggin,4/03/2017,Yarra,Northern Metropolitan
4,6.0,4.0,1600000.0,2.5,3067.0,3.0,1.0,2.0,120.000000,142.000000,...,144.99410,4019.0,Abbotsford,55a Park St,h,VB,Nelson,4/06/2016,Yarra,Northern Metropolitan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18391,23540.0,2.0,622500.0,6.8,3016.0,2.0,2.0,1.0,558.116371,89.000000,...,144.90484,6380.0,Williamstown,8/2 Thompson St,t,SP,Greg,26/08/2017,Moreland,Western Metropolitan
18392,23541.0,4.0,2500000.0,6.8,3016.0,4.0,1.0,5.0,866.000000,157.000000,...,144.89299,6380.0,Williamstown,96 Verdon St,h,PI,Sweeney,26/08/2017,Moreland,Western Metropolitan
18393,23544.0,4.0,1100000.0,12.7,3085.0,4.0,3.0,2.0,558.116371,151.220219,...,145.10547,1369.0,Yallambie,17 Amaroo Wy,h,S,Buckingham,26/08/2017,Moreland,Northern Metropolitan
18394,23545.0,4.0,1285000.0,6.3,3013.0,4.0,1.0,1.0,362.000000,112.000000,...,144.88449,6543.0,Yarraville,6 Agnes St,h,SP,Village,26/08/2017,Moreland,Western Metropolitan
18395,23546.0,4.0,1050000.0,6.3,3013.0,4.0,2.0,2.0,558.116371,139.000000,...,144.87404,6543.0,Yarraville,33 Freeman St,h,VB,Village,26/08/2017,Moreland,Western Metropolitan